---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      ycshin: nginx
  template:
    metadata:
      name: nginx-webserver
      labels:
        ycshin: nginx
    spec:
      containers:
      - name: nginx-webserver
        image: ycshin/nginx-webserver:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ycshin-nginx-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31080
  selector:
    ycshin: nginx
