--- 
apiVersion: v1
kind: Service
metadata:
  name: ycshin-nginx-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31080
  selector:
    ycshin: nginx
    app: nginx-webserver